EVAL:
    dataset: 'cropsr'               # dataset name (cropsr for agricultural aerial images)
    model: 'ot'                     # model (ot, rectified)
    root: './'                      # root directory for the experiment
    seed: 42                        # random seed for reproducibility
    batch_size_train: 4             # batch size for training (using 2 GPUs, 512x512 images)
    num_epoch: 200                  # number of epochs for training (increased for better convergence)
    lr: 0.0001                      # learning rate 与其他数据集保持一致
    train: True                     # train the flow model if True
    lipschitz_constraint: None      # soft constraint on the spectral norm of the Jacobian
    finetune: False                 # finetuning of the model
    eval: True                      # evaluate the flow model if True
    eval_split: 'test'              # data used for evaluation (val, test)
    compute_metrics: False          # compute scores (FID, SW, Vendi) if True
    compute_lipschitz: False
    problem: 'superresolution'      # inverse problem type (superresolution, inpainting, denoising)
    method: 'pnp_flow'              # method for solving inverse problem (pnp_flow, map_gd, d_flow)
    max_batch: 2                    # number of batches of size 4 for evaluation
    batch_size_ip: 4                # inference batch size for 2 GPUs
    noise_type: 'gaussian'          # noise type for inverse problem (gaussian, poisson))
    compute_memory: False
    compute_time: False
    save_results: True
